#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


INCLUDE_PATTERN = re.compile(r"^@(?P<path>\S+)\s*$")


def render_template(template_path: Path, root: Path, seen: set[Path]) -> str:
    resolved_template = template_path.resolve()
    if resolved_template in seen:
        chain = " -> ".join(str(path) for path in [*seen, resolved_template])
        raise RuntimeError(f"circular include detected: {chain}")

    seen.add(resolved_template)
    lines = template_path.read_text(encoding="utf-8").splitlines()
    rendered: list[str] = []

    for line in lines:
        match = INCLUDE_PATTERN.match(line)
        if not match:
            rendered.append(line)
            continue

        include_rel_path = Path(match.group("path"))
        if include_rel_path.is_absolute():
            raise RuntimeError(f"absolute include paths are not allowed: {match.group('path')}")

        normalized_include = Path(os.path.normpath(include_rel_path.as_posix()))
        if normalized_include.parts and normalized_include.parts[0] == "..":
            raise RuntimeError(f"include escapes workspace root: {match.group('path')}")

        include_path = (root / normalized_include).resolve()

        if not include_path.is_file():
            raise RuntimeError(f"include target not found: {match.group('path')}")

        rendered.append(f"<!-- BEGIN INCLUDE: {match.group('path')} -->")
        rendered.append(render_template(include_path, root, seen.copy()))
        rendered.append(f"<!-- END INCLUDE: {match.group('path')} -->")

    return "\n".join(rendered) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Render AGENTS.md from a template with @file includes.")
    parser.add_argument(
        "--template",
        default="AGENTS-template.md",
        help="Path to the template file relative to the workspace root.",
    )
    parser.add_argument(
        "--output",
        default="AGENTS.md",
        help="Path to the output file relative to the workspace root.",
    )
    args = parser.parse_args()

    root = Path.cwd().resolve()
    template_path = (root / args.template).resolve()
    output_path = (root / args.output).resolve()

    if not template_path.is_file():
        print(f"template not found: {template_path}", file=sys.stderr)
        return 1

    try:
        rendered = render_template(template_path, root, set())
    except RuntimeError as exc:
        print(str(exc), file=sys.stderr)
        return 1

    output_path.write_text(
        "<!-- Generated by scripts/render_agents.py from AGENTS-template.md. Do not edit AGENTS.md directly. -->\n\n"
        + rendered + "<!-- Edit AGENTS-template.md when you want to update AGENTS.md, then run: python3 scripts/render_agents.py -->",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
